language: python
python:
  - "3.6"
services:
  - docker

jobs:
  include:

    - stage: Test "Development" Docker Image
      if: tag IS present
      script: scripts/build-run/build.sh -d
      # (_identical_ to production build except for -e
      # local directory package install indstead of PyPI.org)

    # - stage: GitHub Release
    #   install: skip
    #   script: skip
    #   deploy:
    #     provider: releases
    #     skip_cleanup: true
    #     api_key:
    #       secure: oaoRtTE3Ryr9jKu83D5PxoQB2ufJ2fYzGnG2qKO384KFHY4Qbs7iCEsa4cehysi3VV35eRtvDx+KL283grVcbFIIVgr90V6RHJRQzmL77tsTO3sU5Uqm8IDJTD9gmidGS7piOdjOeytxh3iljesRxTmbkLMOyxMADLD/IIfD/aEIvs+gNt0r/8DsTYh7um5r+zxUV4MeXKRs5EOPKoZ5oL3TJ8kIdHeFrlzf8QW1AHmBxk6dzPQoSmBfPZyNkhR9+99HvMoDFRC09PDZbzKeCGFNOAWrSkexAqb3nELr+F3CDmvpHn8nmeV16fza1KpRlgEI/qLAVQbuSs9n55e9J/Xj39wUYV5vQ3SJZBx+fowEG3vAwlh7I7jJxDveiLJFxCb8l40igPJ5G17AowZIylILRAmslXDFcAFpLmMKiyjqHyNtc9R8L0wmnlriuRMF8PaG3wrA/1CitjWFMv58drlFBROSR6mzdcYktZVYUoz8XEYlGeyvblt+pqVgSDs6VYu6sb1WMTxhoO4uWMvAqvVjPuwLGp1wg6KfhkYSmTFFu7ySTjIsYf6CV9Q1ZGkhRBSlWQnYFrESeO8yuFiVxUtveTzZk8WQI8S75cfxWl55nd76HtrBRf4Rz1I2Sjt4hS3Ast67VsHJ0DzekLA7G3vDVQbW5s+qJx+jLU3NBHU=
    #     on:
    #       tags: true

    - stage: PyPI Package
      install: pip install --upgrade pip
      script: skip
      before_deploy: cd hackoregon_examplar && echo __version__ = \'"$TRAVIS_TAG"\' > VERSION
      deploy:
        provider: pypi
        skip_cleanup: true
        user: __token__
        password:
          secure: Hrv29cokx88yq30L6abYOHOXxj5h35aBhhbcr0Bf6FQ2nxGXvoQDCeI6Ahx17oqU/biwIAECcYbGqFIZtE+Q2Uci1g3G1nqOrsKCbzB8Cjvq5Gdj0z79mYVd3oLnj5cUKEsMwEosP6SMRqC0Zs58DhNB4olbMZXSRVMh8eEViwSmXNc4RhOmwS78Q2nm7SAgegnvKdRgu46LTZsivEU4iA6cGjDd3VNxLOD1RJ7a/oFobYIShdvETb9tgzPc0ALC7OUVBUlN3sGMzHjUK3RDdz2nBswnTYrYBhkF5MV+af+mZ1qXI7Bmr7go0pPmIKalZn0NGVofw+YUWVhqNlm9gafh4eX1WWQBVTh0wekyGpKJ/qjO9eeysWKAWfJkucc/6QyE7sftcdszv8cKvAKYmmUX7eGHSWxbMIeg0pF1rtRpFI4fPp9cIJqCb8+IKLml3aAHu5ypQzjaa1Li04Z7XsyckOubqE/wSKnqla80CYV1r8HXenzbRoc/DfHWx8lM6CNhg/YbGMa1S6LGSpvo8zAnPst6HbnaxnmFzJbUUaag5Rw23JmDSH9w+RBFBQuZyNFii1VINKycJxs8/FReyUc+lQEAXhgxpXmAG7kpvly3uL4YEamH48OULBubwKTufbejKCDOf2U0l1T+dimiNqe1YD52dTbeIRCvEmSAIPM=
        distributions: sdist bdist_wheel
        on:
          tags: true

    - stage: Docker Image
      install: scripts/deploy/fetch-scripts.sh
      script: scripts/build-run/build.sh -p
      before_deploy: pip install awscli
      deploy:
        provider: script
        skip_cleanup: true
        script: scripts/deploy/deploy.sh
        on:
          tags: true
